---
engines:
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  csslint:
    enabled: true
  scsslint:
    enabled: true
  markdownlint:
    enabled: true
  stylelint:
    enabled: true
    channel: 'beta'
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:

ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.md"
  - "assets/stylesheets/**.scss"
  - "_sass/**.scss"

exclude_paths:
  - vendor/
