---
engines:
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  csslint:
    enabled: true
  scsslint:
    enabled: true
  markdownlint:
    enabled: true
  stylelint:
    enabled: true
    channel: 'beta'
  shellcheck:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:

ratings:
  paths:
  - "**.md"
  - "_sass/**.scss"
  - "assets/stylesheets/**.css"
  - "assets/stylesheets/**.scss"
  - "bin/**"
  - Gemfile.lock

exclude_paths:
  - "vendor/"
  - "assets/stylesheets/semantic/"
